// QUIZ APP TYPE CONSTANTS
export const FETCH_QUESTIONS = 'FETCH_QUESTIONS';
export const START_QUIZ = 'START_QUIZ';
export const SET_PRESET_ID = 'SET_PRESET_ID';

// QUESTION TYPE CONSTANTS
export const VALIDATE_CHOICE = 'VALIDATE_CHOICE';
export const DELETE_QUESTION = 'DELETE_QUESTION';

// CREATE QUIZ TYPE CONSTANTS
export const SORT_QUESTION = 'SORT_QUESTION';
export const OPEN_CREATE_MODAL = 'OPEN_CREATE_MODAL';
export const OPEN_EDIT_MODAL = 'OPEN_EDIT_MODAL';
export const SAVE_EDITED_QUESTION = 'SAVE_EDITED_QUESTION';
export const CREATE_CUSTOM_QUESTION = 'CREATE_CUSTOM_QUESTION';
export const SAVE_PRESET = 'SAVE_PRESET';

// SCOREBOARD TYPE CONSTANTS
export const UPDATE_SCORE = 'UPDATE_SCORE';
export const UPDATE_PLAYER_NAME = 'UPDATE_PLAYER_NAME';
export const ADD_PLAYER = 'ADD_PLAYER';
export const REMOVE_PLAYER = 'REMOVE_PLAYER';

// MODAL TYPE CONSTANTS
export const SHOW_MODAL = 'SHOW_MODAL';

// TOOLBAR TYPE CONSTANTS
export const EDIT_MODE = 'EDIT_MODE';
export const DELETE_MODE = 'DELETE_MODE';

// MISC TYPE CONSTANTS
export const REHYDRATE_STATE = 'REHYDRATE_STATE';
