// QUIZ APP TYPE CONSTANTS
export const FETCH_QUESTIONS = 'FETCH_QUESTIONS';
export const START_QUIZ = 'START_QUIZ';

// QUESTION TYPE CONSTANTS
export const VALIDATE_CHOICE = 'VALIDATE_CHOICE';

// CREATE QUIZ TYPE CONSTANTS
export const SORT_QUESTION = 'SORT_QUESTION';
export const OPEN_CREATE_MODAL = 'OPEN_CREATE_MODAL';

// MISC TYPE CONSTANTS
export const REHYDRATE_STATE = 'REHYDRATE_STATE';
